/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: c1c4d20e-477c-4964-b07c-d8f6f9615bc3

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Mathlib contains strong foundations for Reinforcement Learning, including the **Martingale Convergence Theorem** (essential for stochastic approximation proofs) and the **Banach Fixed Point Theorem** (essential for Bellman updates).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Mathlib contains foundational theorems for Reinforcement Learning, such as the Martingale Convergence Theorem (for stochastic approximation) and Fixed Point Theorems (for contraction mappings like the Bellman operator), though it lacks specific MARL algorithms or Nash Equilibrium definitions.
-/

-- 1. Martingale Convergence Theorem (Foundational for RL convergence)
#check MeasureTheory.Martingale.ae_eq_condExp_limitProcess

-- 2. Banach Fixed Point Theorem (Foundational for Bellman equations / Contraction Mappings)
#check ContractingWith.fixedPoint

-- 3. Fixed Point on Intervals (1D Brouwer / Intermediate Value Theorem)
#check exists_mem_Icc_isFixedPt
